dataset:
  name: ROAD
  raw_dir: data/raw/road
  ingest_adapter: road_raw
  variant: masquerade
  exclude_files: null
  interim_path: data/interim/canonical.parquet
  prepared_path: data/interim/prepared.parquet
  processed_dir: data/processed/current

prepare:
  label_schema: road
  features: 
    - deltatime
    - delta_id

split:
  unit: window
  val_ratio: 0.2
  test_ratio: 0.2
  window_size: 15
  stride: 15
  downsample: false
  random_seed: 42
  strategy: stratified_random
  # val_sessions:
  #   - Pre_train_D_1
  #   - Pre_train_S_1
  # test_sessions:
  #   - Pre_train_D_2
  #   - Pre_train_S_2

experiment:
  model: mlp_window

model:
  can_ae_transformer:
    d_model: 10
    num_heads: 10
    num_layers: 6
    dim_feedforward: 2048
    dropout: 0.1
    granularity: 1e-8
    max_time_position: 10000
  can_bigrubert:
    max_length: 22
    bert_checkpoint: bert-base-uncased
    tokenizer_checkpoint: bert-base-uncased
    bigru_hidden_size: 512
    dropout: 0.1
  mlp:
    can_id_bits: 11
  mlp_window:
    can_id_bits: 11
    hidden_dims: [32, 16]
    dropout: false

training:
  can_ae_transformer:
    batch_size: 32
    epochs: 100
    learning_rate: 0.0001
    warmup_steps: 100
  mlp:
    batch_size: 256
    epochs: 100
    learning_rate: 0.001
  can_bigrubert:
    batch_size: 16
    epochs: 20
    learning_rate: 0.001
    weight_decay: 0.00001
    early_stopping_patience: 10
    early_stopping_min_delta: 0.0001
  mlp_window:
    batch_size: 32
    epochs: 100
    learning_rate: 0.001

mlflow:
  tracking_uri: "https://dagshub.com/ayasy-el/FedCAN-IDS.mlflow"
  experiment_can_ae_transformer: "can_ae_transformer"
  experiment_mlp: "can_ids_mlp"
  experiment_mlp_window: "can_ids_mlp_window"
  experiment_can_bigrubert: "can_bigrubert"
